### ISSUE TITLE
升级了Home Assistant 2023.6.0，插件报错

### ISSUE THREAD

**Issue by mrchenxc168** [dscao/openwrt#2]
版本号：Home Assistant 2023.6.0

日志：
2023-06-09 22:36:19.888 ERROR (MainThread) [custom_components.openwrt] Unexpected error fetching openwrt data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openwrt/__init__.py", line 128, in _async_update_data
    openwrtinfodata = await self._fetcher._get_openwrt_version(sysauth)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openwrt/data_fetcher.py", line 225, in _get_openwrt_version
    openwrtinfo["device_name"] = re.findall(r"<meta name=\"application-name\" content=\"(.+?) - LuCI", resdata)[0]
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by dscao** [comment]
fixed
