### ISSUE TITLE
正在重试设置

### ISSUE THREAD

**Issue by lumia1998** [dscao/openwrt#3]
Istore os的openwrt无法接入

此错误来自自定义集成。

Logger: custom_components.openwrt
Source: custom_components/openwrt/data_fetcher.py:76
Integration: openwrt (documentation, issues)
First occurred: 11:49:08 (5 occurrences)
Last logged: 11:49:36

Unexpected error fetching openwrt data: "name='sysauth', domain=None, path=None"
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openwrt/__init__.py", line 123, in _async_update_data
    sysauth = await self.get_access_token()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openwrt/__init__.py", line 112, in get_access_token
    self._token = await self._fetcher._login_openwrt()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openwrt/data_fetcher.py", line 93, in _login_openwrt
    resdata = await self._hass.async_add_executor_job(self.requestpost_cookies, url, header, body)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openwrt/data_fetcher.py", line 76, in requestpost_cookies
    resdata = responsedata.cookies["sysauth"]
              ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='sysauth', domain=None, path=None"



Logger: homeassistant.config_entries
Source: config_entries.py:1247
First occurred: 11:49:31 (1 occurrences)
Last logged: 11:49:31

Config entry 'OpenWrt' for openwrt integration not ready yet: None; Retrying in background






Logger: homeassistant.config_entries
Source: config_entries.py:429
First occurred: 11:49:08 (1 occurrences)
Last logged: 11:49:08

Config entry 'OpenWrt' for openwrt integration not ready yet: None; Retrying in background

**Comment by dscao** [comment]
openwrt的分支比较多，数据格式有一点差异，目前只支持基于 https://github.com/coolsnowwolf/lede 的openwrt，其它的可能不支持。
